# Generated by Django 6.0 on 2026-01-02 21:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prospect", "Prospect"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("lost", "Lost"),
                        ],
                        default="prospect",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("partner", "Partner"),
                            ("vendor", "Vendor"),
                        ],
                        default="customer",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1–10"),
                            ("11-50", "11–50"),
                            ("51-200", "51–200"),
                            ("200+", "200+"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_invalid",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "billing_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_street",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_user"], name="core_accoun_owner_u_1c2d7e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="core_accoun_status_468bae_idx"
                    ),
                    models.Index(
                        fields=["is_invalid"], name="core_accoun_is_inva_e11738_idx"
                    ),
                ],
            },
        ),
    ]
