# Generated by Django 6.0 on 2026-03-04 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("mobile", models.CharField(blank=True, max_length=50, null=True)),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("decision_maker", "Decision Maker"),
                            ("influencer", "Influencer"),
                            ("user", "User"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "seniority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "Junior"),
                            ("senior", "Senior"),
                            ("executive", "Executive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("primary_contact", models.BooleanField(default=False)),
                (
                    "preferred_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("none", "None"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("opt_in_email", models.BooleanField(default=True)),
                ("opt_in_sms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_invalid",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to="core.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account"], name="core_contac_account_f87606_idx"
                    ),
                    models.Index(
                        fields=["owner_user"], name="core_contac_owner_u_b3a177_idx"
                    ),
                    models.Index(fields=["role"], name="core_contac_role_665f61_idx"),
                    models.Index(
                        fields=["seniority"], name="core_contac_seniori_e1f1c8_idx"
                    ),
                    models.Index(
                        fields=["is_invalid"], name="core_contac_is_inva_559876_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email__isnull", False)),
                        fields=("account", "email"),
                        name="unique_contact_email_per_account",
                    )
                ],
            },
        ),
    ]
