# Generated by Django 6.0 on 2026-03-09 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usd", "USD"),
                            ("eur", "EUR"),
                            ("gbp", "GBP"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("probability", models.IntegerField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lead", "Lead"),
                            ("qualified", "Qualified"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("open", "Open"), ("won", "Won"), ("lost", "Lost")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "loss_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lead_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("referral", "Referral"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_invalid",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="core.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealContactAssoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_assocs",
                        to="core.contact",
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_assocs",
                        to="core.deal",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["account"], name="core_deal_account_e84e86_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["owner_user"], name="core_deal_owner_u_109d43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["stage"], name="core_deal_stage_c7f31c_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["status"], name="core_deal_status_90c76e_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["is_invalid"], name="core_deal_is_inva_33b059_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dealcontactassoc",
            constraint=models.UniqueConstraint(
                fields=("deal", "contact"), name="unique_deal_contact"
            ),
        ),
    ]
