# Generated by Django 6.0 on 2026-05-06 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('follow_up', 'Follow Up'), ('admin', 'Admin'), ('customer', 'Customer')], max_length=20, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_detail', to='core.activity')),
            ],
            options={
                'ordering': ['-activity__created_at'],
            },
        ),
    ]
