# Generated by Django 6.0 on 2026-06-04 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_meeting_meetinguserassoc_meetingcontactassoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("connected", "Connected"),
                            ("no_answer", "No Answer"),
                            ("voicemail", "Voicemail"),
                            ("busy", "Busy"),
                            ("wrong_number", "Wrong Number"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_detail",
                        to="core.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity__created_at"],
                "indexes": [
                    models.Index(
                        fields=["direction"], name="core_call_directi_a1d191_idx"
                    ),
                    models.Index(
                        fields=["outcome"], name="core_call_outcome_d1f7d8_idx"
                    ),
                ],
            },
        ),
    ]
