# Generated by Django 6.0 on 2026-06-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_note_and_notevisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_overdue',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account'),
        ),
        migrations.AlterField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deal'),
        ),
    ]
