# Generated by Django 6.0 on 2026-06-09 19:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activity_is_overdue_alter_note_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('source_service', models.CharField(choices=[('core', 'Core'), ('activities', 'Activities'), ('automation', 'Automation')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emitted_by_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type'], name='core_event_event_t_79dbe0_idx'), models.Index(fields=['source_service'], name='core_event_source__e1de4a_idx'), models.Index(fields=['entity_type'], name='core_event_entity__2e9ca4_idx'), models.Index(fields=['entity_id'], name='core_event_entity__dbe292_idx'), models.Index(fields=['occurred_at'], name='core_event_occurre_eedf4c_idx')],
            },
        ),
    ]
