# Generated by Django 6.0 on 2026-06-10 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("conditions", models.JSONField()),
                ("evaluation_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_invalid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="core.trigger",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["evaluation_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["trigger"], name="core_rule_trigger_6c55a8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_rule_is_acti_23f431_idx"
                    ),
                    models.Index(
                        fields=["is_invalid"], name="core_rule_is_inva_f76dbe_idx"
                    ),
                    models.Index(
                        fields=["evaluation_order"], name="core_rule_evaluat_0b8376_idx"
                    ),
                ],
            },
        ),
    ]
