# Generated by Django 6.0 on 2026-06-11 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_executionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create_task", "Create Task"),
                    ("update_deal_stage", "Update Deal Stage"),
                    ("assign_owner", "Assign Owner"),
                    ("add_note", "Add Note"),
                    ("emit_event", "Emit Event"),
                ],
                default="create_task",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="is_invalid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="action",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="retry_policy",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="timeout_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="action",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="action",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="action",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["action_type"], name="core_action_action__2ca46e_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["is_invalid"], name="core_action_is_inv_23287b_idx"),
        ),
    ]